--DROPPING TABLE IF EXISTS

DROP TABLE ADMIN;
DROP TABLE INVENTORY;


--DROPPING AS PER REFERENCED

--DROPPING TABLE PURCHASE
DROP TABLE PURCHASE;

--DROPPING TABLE FARMER
DROP TABLE FARMER;

--DROPPING TABLE SALE
DROP TABLE SALE;

--DROPPIN TABLE BUYER
DROP TABLE BUYER;

-----------------------------------------------------------------------------
--DROPPING SQUENCE IF EXIST
DROP SEQUENCE SALE_SEQ;
DROP SEQUENCE BUY_SEQ;
DROP SEQUENCE PUR_SEQ;
DROP SEQUENCE FAR_SEQ;
DROP SEQUENCE BILL_SEQ;
DROP SEQUENCE BUYBILL_SEQ;

---===============================================================================
--CRATING SEQUENCE FOR EMPLOYEE ID 

CREATE SEQUENCE FAR_SEQ
MINVALUE 1
MAXVALUE 9999999999999
START WITH 1
INCREMENT BY 1;
-------------------------------------------------------------------------------------------------------------


--CREATING SEQUENCE FOR PURCHASE ID
CREATE SEQUENCE PUR_SEQ
MINVALUE 100
MAXVALUE 9999999999999
START WITH 100
INCREMENT BY 1;

--------------------------------------------------------------------------------------------------------------------
--CREATING SEQUENCE FOR BUYER ID
CREATE SEQUENCE BUY_SEQ
MINVALUE 200
MAXVALUE 9999999999999
START WITH 200
INCREMENT BY 1;

--------------------------------------------------------------------------------------------------------------------
--CREATING SEQUENCE FOR SALE ID
CREATE SEQUENCE SALE_SEQ
MINVALUE 300
MAXVALUE 9999999999999
START WITH 300
INCREMENT BY 1;

-----------------------------------------------------------------------------------------------------------------------
--CREATING SEQUENCE FOR FORMER BILL NUMBER
CREATE SEQUENCE BILL_SEQ
MINVALUE 1000
MAXVALUE 9999999999999
START WITH 1000
INCREMENT BY 1;



---------------------------------------------------------------------------------------------------------
--CREATING SEQUENCE FOR FORMER BUYER BILL NUMBER
CREATE SEQUENCE BUYBILL_SEQ
MINVALUE 2000
MAXVALUE 9999999999999
START WITH 2000
INCREMENT BY 1;



---------------------------------------------------------------------------------------------------------

--CREATING ADMIN TABLE

CREATE TABLE ADMIN(ADMIN_ID NUMBER(5) PRIMARY KEY,ADMIN_NAME VARCHAR2(30) UNIQUE,PASSWORD VARCHAR2(20) NOT NULL);

--INSERTING ADMIN VALUSES
INSERT INTO ADMIN(ADMIN_ID,ADMIN_NAME,PASSWORD) VALUES(11,'SUJAY','AGRISUJAY');

----------------------------------------------------------------------------------------------------------
--CREATING TABLE FARMER

CREATE TABLE FARMER(FARMER_ID NUMBER(5) PRIMARY KEY,FARMER_NAME VARCHAR2(30),MOB_NO VARCHAR2(10));

--INSERTING DEFAULT VALUE INTO FARMER TABLE
INSERT INTO FARMER(FARMER_ID,FARMER_NAME,MOB_NO) VALUES(FAR_SEQ.NEXTVAL,'BALAKRISHNA','9448347983');
-----------------------------------------------------------------------------------------------------------



--CREATING PURCHASE TABLE
CREATE TABLE PURCHASE(PURCHASE_ID NUMBER(5) PRIMARY KEY,FARMER_ID NUMBER(5),BILL_NO NUMBER(10) UNIQUE,COMODITY VARCHAR2(20) NOT NULL,QTY NUMBER(20) NOT NULL,P_DATE DATE NOT NULL,FOREIGN KEY(FARMER_ID) REFERENCES FARMER(FARMER_ID));

--INSERTING DEFAULT VALUES INTO PURCHASE TABLE
INSERT INTO PURCHASE(PURCHASE_ID,FARMER_ID,BILL_NO,COMODITY,QTY,P_DATE) VALUES(PUR_SEQ.NEXTVAL,FAR_SEQ.CURRVAL,BILL_SEQ.NEXTVAL,'PADDY',20,TO_DATE('2018/11/09','YYYY/MM/DD'));
-------------------------------------------------------------------------------------------------------------

--CREATING INVENTORY TABLE

CREATE TABLE INVENTORY(INVENTORY_ID NUMBER(5) PRIMARY KEY,COMODITY VARCHAR2(20) NOT NULL,QTY NUMBER(20) NOT NULL);

--INSERTING DEFAULT VALUES INTO INVENTORY TABLE
 
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(1,'PADDY',50);
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(2,'WHEAT',50);
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(3,'RAGI',50);
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(4,'COFFEE',50);
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(5,'PEPPER',50);
INSERT INTO INVENTORY(INVENTORY_ID,COMODITY,QTY) VALUES(6,'BARLI',50);

----------------------------------------------------------------------------------------------------------
--CREATING TABLE BUYER

CREATE TABLE BUYER(BUYER_ID NUMBER(5) PRIMARY KEY,BUYER_NAME VARCHAR2(30) NOT NULL,MOB_NO VARCHAR2(10));

INSERT INTO BUYER(BUYER_ID,BUYER_NAME,MOB_NO) VALUES(BUY_SEQ.NEXTVAL,'SANJAY','7740125412');

----------------------------------------------------------------------------------------------------------
--CREATE TABLE SALE

CREATE TABLE SALE(SALE_ID NUMBER(5) PRIMARY KEY,BUYER_ID NUMBER(5),BILL_NO VARCHAR2(20) NOT NULL,COMODITY VARCHAR2(20) NOT NULL,QTY NUMBER(20) NOT NULL,SDATE DATE,FOREIGN KEY(BUYER_ID) REFERENCES BUYER(BUYER_ID));

INSERT INTO SALE(SALE_ID,BUYER_ID,BILL_NO,COMODITY,QTY,SDATE) VALUES(SALE_SEQ.NEXTVAL,BUY_SEQ.CURRVAL,BUYBILL_SEQ.NEXTVAL,'PADDY',0,TO_DATE('2018/11/09','YYYY/MM/DD'));

------------------------------------------------------------------------------------------------------------


